import Head from "next/head";
import MainNavbar from "../component/navbar/MainNavbar";
import { ParallaxProvider } from 'react-scroll-parallax';
import CartProvider from '../provider/cart'
import '../styles/globals.css'
import "../theme/core.css";
import ItemsProvider from "../provider/parallax";

function MyApp({ Component, pageProps }) {
  return (

    <>
      <Head>
        
        <title>PlayCBD</title>
        
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CartProvider>
  
          <MainNavbar />
      
          <Component {...pageProps} >
          </Component>
   
         
            
         
    
      </CartProvider>

    </>


  )
}

export default MyApp
